In [4]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

Telco = pd.read_csv (r'/Users/mindyshiben/codeup-data-science/Telco.csv')
print (Telco)

     customer_id  gender  is_senior_citizen partner dependents  phone_service  \
0     0002-ORFBO  Female                  0     Yes        Yes              1
1     0003-MKNFE    Male                  0      No         No              2
2     0004-TLHLJ    Male                  0      No         No              1
3     0011-IGKFF    Male                  1     Yes         No              1
4     0013-EXCHZ  Female                  1     Yes         No              1
...          ...     ...                ...     ...        ...            ...
7044  9987-LUTYD  Female                  0      No         No              1
7045  9992-RRAMN    Male                  0     Yes         No              2
7046  9992-UJOEL    Male                  0      No         No              1
7047  9993-LHIEB    Male                  0     Yes        Yes              1
7048  9995-HOTOH    Male                  0     Yes        Yes              0

      internet_service  contract_type      payment_type  monthly_charges  ...  \
0                    1              1      Mailed check            65.60  ...
1                    1              0      Mailed check            59.90  ...
2                    2              0  Electronic check            73.90  ...
3                    2              0  Electronic check            98.00  ...
4                    2              0      Mailed check            83.90  ...
...                ...            ...               ...              ...  ...
7044                 1              1      Mailed check            55.15  ...
7045                 2              0  Electronic check            85.10  ...
7046                 1              0      Mailed check            50.30  ...
7047                 1              2      Mailed check            67.85  ...
7048                 1              2  Electronic check            59.00  ...

      has_churned has_internet  has_phone  has_phone_and_internet  \
0           False         True       True                    True
1           False         True       True                    True
2            True         True       True                    True
3            True         True       True                    True
4            True         True       True                    True
...           ...          ...        ...                     ...
7044        False         True       True                    True
7045         True         True       True                    True
7046        False         True       True                    True
7047        False         True       True                    True
7048        False         True      False                   False

      partner_dependents  monthly_average  validate      phone_details  \
0                      3            65.92     False           One Line
1                      0             9.06     False  Two or More Lines
2                      0             3.80     False           One Line
3                      1            12.63     False           One Line
4                      1             3.19     False           One Line
...                  ...              ...       ...                ...
7044                   0            13.47     False           One Line
7045                   1            22.02     False  Two or More Lines
7046                   0             1.84     False           One Line
7047                   3            68.20     False           One Line
7048                   3            62.84     False   No Phone Service

      rounded_tenure  type_of_service
0                9.0   internet+phone
1                9.0   internet+phone
2                4.0   internet+phone
3               13.0   internet+phone
4                3.0   internet+phone
...              ...              ...
7044            13.0   internet+phone
7045            22.0   internet+phone
7046             2.0   internet+phone
7047            68.0   internet+phone
7048            63.0         internet

[7049 rows x 24 columns]

In [3]:
Telco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7049 entries, 0 to 7048
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             7049 non-null   object
 1   gender                  7049 non-null   object
 2   is_senior_citizen       7049 non-null   int64
 3   partner                 7049 non-null   object
 4   dependents              7049 non-null   object
 5   phone_service           7049 non-null   int64
 6   internet_service        7049 non-null   int64
 7   contract_type           7049 non-null   int64
 8   payment_type            7049 non-null   object
 9   monthly_charges         7049 non-null   float64
 10  total_charges           7038 non-null   float64
 11  churn                   7049 non-null   object
 12  tenure                  7049 non-null   float64
 13  is_female               7049 non-null   bool
 14  has_churned             7049 non-null   bool
 15  has_internet            7049 non-null   bool
 16  has_phone               7049 non-null   bool
 17  has_phone_and_internet  7049 non-null   bool
 18  partner_dependents      7049 non-null   int64
 19  monthly_average         7049 non-null   float64
 20  validate                7049 non-null   bool
 21  phone_details           7049 non-null   object
 22  rounded_tenure          7049 non-null   float64
 23  type_of_service         7049 non-null   object
dtypes: bool(6), float64(5), int64(5), object(8)
memory usage: 1.0+ MB

In [5]:
Telco.head()

,customer_id,gender,is_senior_citizen,partner,dependents,phone_service,internet_service,contract_type,payment_type,monthly_charges,...,has_churned,has_internet,has_phone,has_phone_and_internet,partner_dependents,monthly_average,validate,phone_details,rounded_tenure,type_of_service
0,0002-ORFBO,Female,0,Yes,Yes,1,1,1,Mailed check,65.6,...,False,True,True,True,3,65.92,False,One Line,9.0,internet+phone
1,0003-MKNFE,Male,0,No,No,2,1,0,Mailed check,59.9,...,False,True,True,True,0,9.06,False,Two or More Lines,9.0,internet+phone
2,0004-TLHLJ,Male,0,No,No,1,2,0,Electronic check,73.9,...,True,True,True,True,0,3.80,False,One Line,4.0,internet+phone
3,0011-IGKFF,Male,1,Yes,No,1,2,0,Electronic check,98.0,...,True,True,True,True,1,12.63,False,One Line,13.0,internet+phone
4,0013-EXCHZ,Female,1,Yes,No,1,2,0,Mailed check,83.9,...,True,True,True,True,1,3.19,False,One Line,3.0,internet+phone

In [17]:
len(Telco[Telco.has_churned == True])

1870

In [18]:
len(Telco[Telco.has_churned == False])

5179

In [32]:
round(len(Telco[Telco.has_churned == True])/len(Telco),2)

0.27

In [33]:
# How many customers have churned?

# 1870, 27%

In [36]:
churned = Telco[Telco.has_churned == True]
churned

,customer_id,gender,is_senior_citizen,partner,dependents,phone_service,internet_service,contract_type,payment_type,monthly_charges,...,has_churned,has_internet,has_phone,has_phone_and_internet,partner_dependents,monthly_average,validate,phone_details,rounded_tenure,type_of_service
2,0004-TLHLJ,Male,0,No,No,1,2,0,Electronic check,73.90,...,True,True,True,True,0,3.80,False,One Line,4.0,internet+phone
3,0011-IGKFF,Male,1,Yes,No,1,2,0,Electronic check,98.00,...,True,True,True,True,1,12.63,False,One Line,13.0,internet+phone
4,0013-EXCHZ,Female,1,Yes,No,1,2,0,Mailed check,83.90,...,True,True,True,True,1,3.19,False,One Line,3.0,internet+phone
18,0022-TCJCI,Male,1,No,No,1,1,1,Credit card (automatic),62.70,...,True,True,True,True,0,44.52,False,One Line,45.0,internet+phone
19,0023-HGHWL,Male,1,No,No,0,1,0,Electronic check,25.10,...,True,True,False,False,0,1.00,False,No Phone Service,1.0,internet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7023,9965-YOKZB,Male,1,No,No,2,2,0,Electronic check,83.85,...,True,True,True,True,0,9.42,False,Two or More Lines,9.0,internet+phone
7031,0032-PGELS,Female,0,Yes,Yes,0,1,0,Bank transfer (automatic),30.50,...,True,True,False,False,3,1.00,False,No Phone Service,1.0,internet
7042,9985-MWVIX,Female,0,No,No,1,2,0,Mailed check,70.15,...,True,True,True,True,0,1.00,False,One Line,1.0,internet+phone
7043,9986-BONCE,Female,0,No,No,1,0,0,Bank transfer (automatic),20.95,...,True,False,True,False,0,4.08,False,One Line,4.0,phone
7045,9992-RRAMN,Male,0,Yes,No,2,2,0,Electronic check,85.10,...,True,True,True,True,1,22.02,False,Two or More Lines,22.0,internet+phone

In [59]:
stayed = Telco[Telco.has_churned == False]
len(stayed)

5179

In [49]:
len(churned[churned.gender == 'Male'])

930

In [50]:
len(churned[churned.gender == 'Female'])

940

In [ ]:
# gender does not seem to play a role in churn

In [56]:
len(churned[churned.is_senior_citizen == 1])/len(churned)
# % of churned customers that are senior

0.2545454545454545

In [55]:
len(Telco[Telco.is_senior_citizen == 1])/len(Telco)
# % of seniors in all customers

0.16200879557384026

In [62]:
seniors = Telco[Telco.is_senior_citizen == 1]

In [60]:
len(stayed[stayed.is_senior_citizen== 1])/len(stayed)

0.1285962541031087

In [ ]:
# senior citizens may be more likely to churn
# amongst customers that stayed, 13% are seniors whereas 25% of churned customers are seniors

In [63]:
groupby.churned.payment_type

NameError: name 'groupby' is not defined